// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/LandingPage.tsx": () => import("../components/mockups/landing/LandingPage.tsx"),
  "./components/mockups/landing/PrivacyPage.tsx": () => import("../components/mockups/landing/PrivacyPage.tsx"),
  "./components/mockups/landing/ThankYou.tsx": () => import("../components/mockups/landing/ThankYou.tsx")
};
